# Generated by Django 3.2 on 2022-04-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='collection',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
