# Generated by Django 3.2 on 2022-04-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
